name: Continuous Integration

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  docs:
    # Deploy docs only when builds succeed
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
      && github.event_name == 'push'
      && github.repository_owner == 'heal-research'

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: sudo apt-get update -q
        && sudo apt-get install doxygen graphviz -q -y

    - name: Build docs
      run: cmake -B build -D "CMAKE_PROJECT_INCLUDE=$PWD/cmake/docs.cmake"
        && cmake --build build --target docs

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        allow_empty_commit: true
